apiVersion: tensorflow.org/v1alpha1
kind: TfJob
metadata:
  name: inception-171202-004416
  namespace: default
spec:
  replicaSpecs:
  - replicas: 1
    template:
      spec:
        containers:
        - args:
          - python
          - tf_cnn_benchmarks.py
          - --num_gpus=1
          - --batch_size=32
          - --model=resnet50
          - --variable_update=parameter_server
          image: gcr.io/cloud-ml-dev/tf-benchmarks-cpu:34c398d-dirty-a2f786d
          name: tensorflow
          workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
        restartPolicy: OnFailure
    tfReplicaType: MASTER
  - replicas: 1
    template:
      spec:
        containers:
        - args:
          - python
          - tf_cnn_benchmarks.py
          - --num_gpus=1
          - --batch_size=32
          - --model=resnet50
          - --variable_update=parameter_server
          image: gcr.io/cloud-ml-dev/tf-benchmarks-gpu:34c398d-dirty-244ca2d
          name: tensorflow
          resources:
            limits:
              nvidia.com/gpu: 1
          workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
        restartPolicy: OnFailure
    tfReplicaType: WORKER
  - replicas: 1
    template:
      spec:
        containers:
        - args:
          - python
          - tf_cnn_benchmarks.py
          - --num_gpus=1
          - --batch_size=32
          - --model=resnet50
          - --variable_update=parameter_server
          image: gcr.io/cloud-ml-dev/tf-benchmarks-cpu:34c398d-dirty-a2f786d
          name: tensorflow
          workingDir: /opt/tf-benchmarks/scripts/tf_cnn_benchmarks
        restartPolicy: OnFailure
    tfReplicaType: PS
  tfImage: gcr.io/cloud-ml-dev/tf-benchmarks-cpu:34c398d-dirty-a2f786d
